spring:
  datasource:
    url: jdbc:mysql://localhost:3306/market
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  elasticsearch:
    uris: http://localhost:9200
logging:
  level:
    org.elasticsearch.client: TRACE
